name: PyTest
on: [push, workflow_dispatch]

jobs:
  test:
    name: Test python scripts
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          sudo apt install -y mupdf-tools poppler-utils
          python3 -m pip install --upgrade pip
          pip3 install pytest pytest-cov pytest-github-actions-annotate-failures jupyter numpy matplotlib
      - name: Test with pytest
        run: |
          jupyter nbconvert --to script jupyter_assignment.ipynb
          jupyter nbconvert --to script matplotlib_assignment.ipynb
          pytest -s jupyter_tests.py
